apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wbdp6r5z5-nodejs 
  janus-idp.io/tekton: wbdp6r5z5-nodejs
  backstage.io/kubernetes-id: wbdp6r5z5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wbdp6r5z5-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml